name: test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Smoke test
        run: ./gradlew :run --args="listx"
      - name: Lint
        run: ./gradlew :detekt